version: "3"
services:
    file-commons:
        image: ostrowskirenan/file-commons:dev
        container_name: filecommons
        ports:
        - 8444:8444
visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8888:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [ node.role == manager ]